<div>
    <h2>
        Pour commencer
    </h2>

    <a href="wiki/index.php/Guide_du_nouvel_arrivant">
                Guide du nouvel arrivant</a>

    <h2>
        Monitoring Gearman
    </h2>

    <?php
    try {
        $monitor = new Default_Model_GearmanMonitor();
    } catch (Exception $e) {
        $monitor = null;
    }
    ?>

    <?php if (!$monitor) : ?>

        <p style="color: darkred; font-weight: bold; font-size: 1.2em">
            <i class="icon-warning-sign"></i>
            Statut de Gearman : KO
        </p>

        <p style="color: darkred">
            Impossible de se connecter à Gearman (localhost).
        </p>

    <?php else : ?>

        <p style="margin-top: 10px">
            Statut de Gearman : OK
        </p>
        <p style="margin-top: 10px">
            Liste des taches enregistrées
        </p>
        <pre><?php
            $monitor = new Default_Model_GearmanMonitor();

            $cmd = 'status';
            $response = $monitor->cmd($cmd);
            Default_Model_GearmanMonitor::showResponse($response, $cmd);
        ?></pre>

        <p style="margin-top: 10px">
            Liste des workers
        </p>
        <pre><?php
            $monitor = new Default_Model_GearmanMonitor();

            $cmd = 'workers';
            $response = $monitor->cmd($cmd);
            Default_Model_GearmanMonitor::showResponse($response, $cmd);
        ?></pre>

    <?php endif; ?>
</div>