<div id="accueil">
<?php
$baseUrl = 'http://dev.myc-sense.com/';
?>
    <h2>
        Pour commencer
    </h2>

    <a href="<?=$baseUrl?>wiki/index.php/Guide_du_nouvel_arrivant">
                Guide du nouvel arrivant</a>

    <h2>
        Infos diverses
    </h2>
    <ul>
        <li>
            La documentation du code de la librairie est générée tous les jours automatiquement.
        </li>
        <li>
            Le rapport de couverture de code des tests est généré tous les jours automatiquement.
            Cette génération est assez longue (5 minutes), ne la relancer via le menu que si
            c'est nécessaire.
        </li>
    </ul>
</div>