<?php
    // Fichier contenant la barre d'entête de l'application.
?>
<ul id="menuGeneral">
    <li>
        <a href="http://mail.google.com/a/myc-sense.com">
            Courriels
        </a>
    </li>
    <li>
        <a href="http://docs.google.com/a/myc-sense.com">
            Documents
        </a>
    </li>
    <li>
        <a href="http://dev.myc-sense.com:3000">
            Redmine
        </a>
    </li>
    <li>
        <a href="http://dev.myc-sense.com:8000">
            phpUnerControl
        </a>
    </li>
    <li>
        <a href="http://dev.myc-sense.com/wiki/">
            Wiki
        </a>
    </li>
    <li>
        <a href="http://dev.myc-sense.com/documentation/voir">
            phpDoc
        </a>
    </li>
</ul>
