<?php
/**
 * @author valentin.claras
 * @package UI
 * @subpackage Layout
 */
    // Fichier contenant le pied de page de l'application.
?>
<footer>
    <ul class="unstyled">
        <li>Interface de gestion des projets MyC-sense</li>
        <li>Package : <?=Core_Package_Manager::getCurrentPackage()->getName()?></li>
        <li>Environnement : <?=APPLICATION_ENV?></li>
        <li>Version : Trunk</li>
    </ul>
</footer>