<?php

$htmlMenu = false;

foreach (Navigation_Model_Menu::getMenusRacine() as $menu) {
    $listeSousMenu = $menu->getEnfants();
    if (!$htmlMenu) {
?>
<div id="bd">
    <div id="yui-main">
        <div class="yui-b">
            <div id="productsandservices" class="yuimenubar yuimenubarnav">
                <div class="bd">

                    <ul class="first-of-type">
<?php
        $htmlMenu = true;
    }
?>
                            <li class="yuimenubaritem">
                                <a class="yuimenubaritemlabel" <?php
                                if ($menu->getPage()) {
                                ?> href="<?=$this->baseURL().$menu->getPage()->url?><?php
                                }
                                ?>"><?=$menu->nom?></a>
                                <div class="yuimenu">
                                    <div class="bd">
                                        <ul>
<?php
            foreach ($listeSousMenu as $sousMenu) {
?>
                                        <li class="yuimenuitem">
                                            <?php
                                            $url = $sousMenu->getPage()->url;
                                            if (strncmp($url, 'http', strlen('http')) !== 0) {
                                                $url = $this->baseURL().$url;
                                            }
                                            ?>
                                            <a class="yuimenuitemlabel" href="<?=$url?>">
                                                <?=$sousMenu->nom?>
                                            </a>
                                        </li>
<?php
            }
?>
                                        </ul>
                                    </div>
                                </div>
                            </li>
<?php
}
if ($htmlMenu) {
?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<?php
}