<?php
$leftMenu = [
    [
        'name' => 'Courriels',
        'url'  =>  'http://mail.google.com/a/myc-sense.com',
    ],
    [
        'name' => 'Documents',
        'url'  =>  'http://docs.google.com/a/myc-sense.com',
    ],
    [
        'name' => 'Redmine',
        'url'  =>  'http://dev.myc-sense.com:3000',
    ],
    [
        'name' => 'phpunderControl',
        'url'  =>  'http://dev.myc-sense.com:8080/cruisecontrol',
    ],
    [
        'name' => 'Wiki',
        'url'  =>  'wiki/',
    ],
    [
        'name' => 'phpDoc',
        'url'  =>  'api/',
    ],
    [
        'name' => 'Munin',
        'url'  =>  'munin',
    ],
    [
        'name'    => 'Library',
        'url'     => null,
        'submenu' => [
            [
                'name' => 'AF',
                'url'  => 'af-trunk/',
            ],
            [
                'name' => 'Classif',
                'url'  => 'classif-trunk/',
            ],
            [
                'name' => 'DW',
                'url'  => 'dw-trunk/',
            ],
            [
                'name' => 'Export',
                'url'  => 'export-trunk/',
            ],
            [
                'name' => 'Inventory',
                'url'  => 'inventory-trunk/',
            ],
            [
                'name' => 'Keyword',
                'url'  => 'keyword-trunk/',
            ],
            [
                'name' => 'Log',
                'url'  => 'log-trunk/',
            ],
            [
                'name' => 'Orga',
                'url'  => 'orga-trunk/',
            ],
            [
                'name' => 'Simulation',
                'url'  => 'simulation-trunk/',
            ],
            [
                'name' => 'Social',
                'url'  => 'social-trunk/',
            ],
            [
                'name' => 'TEC',
                'url'  => 'tec-trunk/',
            ],
            [
                'name' => 'Techno',
                'url'  => 'techno-trunk/',
            ],
            [
                'name' => 'UI',
                'url'  => 'ui-trunk/',
            ],
            [
                'name' => 'Unit',
                'url'  => 'unit-trunk/',
            ],
            [
                'name' => 'User & ACL',
                'url'  => 'user-trunk/',
            ],
        ],
    ],
    [
        'name'    => 'Applications',
        'url'     => null,
        'submenu' => [
            [
                'name' => 'Démo',
                'url'  => 'demo/',
            ],
            [
                'name' => 'Stations de Montagne',
                'url'  => 'stations-montagne/',
            ],
            [
                'name' => 'Spiritueux',
                'url'  => 'spiritueux/',
            ],
            [
                'name' => 'Bolloré',
                'url'  => 'bollore/',
            ],
            [
                'name' => 'Bilan Carbone Campus',
                'url'  => 'bc-campus/',
            ],
        ],
    ],
    [
        'name'    => 'Applications archivées',
        'url'     => null,
        'submenu' => [
            [
                'name' => 'Basecarbone version 0.2',
                'url'  => 'basecarbone2/',
            ],
            [
                'name' => 'Basecarbone version 0.3',
                'url'  => 'basecarbone/',
            ],
        ],
    ],
];

?>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <button class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="index">My C-Tool - Supervision</a>

            <div class="nav-collapse">
                <ul class="nav">
                    <?php foreach ($leftMenu as $node) {
                        $liClasses = array();
                        if (isset($node['active']) && $node['active']) {
                            $liClasses[] = 'active';
                        }
                        if (isset($node['submenu']) && (count($node['submenu']) > 0)) {
                            $liClasses[] = 'dropdown';
                        }
                        $liClass = (count($liClasses) > 0) ? ' class="' . implode(' ', $liClasses) . '"' : '';
                        $mainLink = (isset($node['url']) && ($node['url'] != '')) ? ' href="' . $node['url'] . '"' : '';
                        ?>
                        <?php
                        if (isset($node['submenu']) && (is_array($node['submenu']))
                            && (count($node['submenu']) > 0)
                        ) {
                            ?>
                            <li<?=$liClass?>>
                                <a<?=$mainLink?> class="dropdown-toggle" data-toggle="dropdown" href="#">
                                    <?=$node['name']?>
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <?php foreach ($node['submenu'] as $submenu) { ?>
                                        <?php
                                        if (isset($submenu['submenu']) && (is_array($submenu['submenu']))
                                            && (count($submenu['submenu']) > 0)
                                        ) {
                                            ?>
                                            <li class="dropdown-submenu">
                                                <a href="<?=$submenu['url']?>"><?=$submenu['name']?></a>
                                                <ul class="dropdown-menu">
                                                    <?php foreach ($submenu['submenu'] as $submenuBis) { ?>
                                                        <li><a href="<?=$submenuBis['url']?>"><?=$submenuBis['name']?></a></li>
                                                    <?php } ?>
                                                </ul>
                                            </li>
                                        <?php } else { ?>
                                            <li><a href="<?=$submenu['url']?>"><?=$submenu['name']?></a></li>
                                        <?php } ?>
                                    <?php } ?>
                                </ul>
                            </li>
                        <?php } else { ?>
                            <li<?=$liClass?>><a<?=$mainLink?>><?=$node['name']?></a></li>
                        <?php } ?>
                    <?php } ?>
                </ul>
            </div>
        </div>
    </div>
</div>
