<div id="bd">
	<!-- Pour changer les valeurs du menu : Changer les valeurs de la hiérarchie <ul> <li> -->
	<div id="yui-main">
		<div class="yui-b">
			<!-- start: stack grids here -->
			<div id="productsandservices" class="yuimenubar yuimenubarnav">
				<div class="bd">
					<ul class="first-of-type">

						<?php
						// Liste des menus racines
						$listeMenus = Mycsense_PagesMenus_Menu::getMenusRacine();
						foreach ($listeMenus as $menu) {
							// Récupération du lien s'il existe
							$lien = '';
							$page = $menu->getPage();
							if($page) {
								$lien = 'href="' . $this->baseURL() . $page->url . '"';
							}
							?>
							<li class="yuimenubaritem">
								<a class="yuimenubaritemlabel" <?=$lien?> >
									<?=$menu->nom?></a>

								<?php
								// Liste des sous-menus
								$listeSousMenu = $menu->getEnfants();
								if (count($listeSousMenu) > 0) {
									?>
									<div id="menu1" class="yuimenu">
										<div class="bd">
											<ul>
												<?php
												foreach($listeSousMenu as $sousMenu) {
													?>
													<li class="yuimenuitem">
														<a 	class="yuimenuitemlabel"
															href="<?=$this->baseURL() . $sousMenu->getPage()->url?>">
															<?=$sousMenu->nom?></a>
													</li>
													<?php
												}
												?>
											</ul>
										</div>
									</div>
									<?php
								}
								?>

							</li>
							<?php
						}
						?>

					</ul>
				</div>
			</div>
			<!-- end: stack grids here -->
		</div>
	</div>
<!-- end: primary column from outer template -->
</div>
