<script type="text/javascript">
	function ouvrir(object) {
		if (object.display = 'none') {
			object.display = 'block';
		} else {
			object.display = 'none';
		}
	}
</script>
<?php
function afficherResultat($tableau)
{
	static $i = 0;
	$i++;
	// Supprime la première ligne
	unset($tableau[0]);
	// Si c'est OK
	if (strpos($tableau[count($tableau)-1], 'OK') !== false) {
		$resultat = 'OK';
		// Style du résumé
		$style = "background: #94D88B;";
	} else {
		$resultat = 'ERREURS';
		// Style du résumé
		$style = "background: #D89C8B;";
	}
	?>
	<p style="<?=$style;?>" onclick="ouvrir(document.getElementById('detailErreurs$i'))">
		Résumé :
		<?=$resultat?>
	</p>
	<pre id="detailErreurs<?=$i?>">
		<?=implode("\n", $tableau);?>
	</pre>
	<?php
}
?>
<h1>
	Tests unitaires
</h1>

<h2>
	Base carbone
</h2>
<?php afficherResultat($this->basecarbone) ?>

<h2>
	Stations de montagne
</h2>
<?php afficherResultat($this->stationsmontagne)?>

<h2>
	Utilisateurs
</h2>
<?php afficherResultat($this->utilisateurs)?>

<h2>
	Unites
</h2>
<?php afficherResultat($this->unites)?>

<h2>
	Pages et menus
</h2>
<pre>
<?php afficherResultat($this->pagesmenus)?>

<h2>
	Acl
</h2>
<?php afficherResultat($this->acl)?>

<h2>
	Langues
</h2>
<?php afficherResultat($this->langues)?>
