<h1>
	Tests unitaires
</h1>

<h2>
	Base carbone
</h2>
<pre>
<?=implode("\n", $this->basecarbone)?>
</pre>

<h2>
	Stations de montagne
</h2>
<pre>
<?=implode("\n", $this->stationsmontagne)?>
</pre>

<h2>
	Utilisateurs
</h2>
<pre>
<?=implode("\n", $this->utilisateurs)?>
</pre>

<h2>
	Unites
</h2>
<pre>
<?=implode("\n", $this->unites)?>
</pre>

<h2>
	Pages et menus
</h2>
<pre>
<?=implode("\n", $this->pagesmenus)?>
</pre>

<h2>
	Acl
</h2>
<pre>
<?=implode("\n", $this->acl)?>
</pre>