<script type="text/javascript">
    function ouvrir(object) {
        if (object.style.display == 'none') {
            object.style.display = 'block';
        } else {
            object.style.display = 'none';
        }
    }

    function decocher() {
        var form = document.forms['tests'];
        var nbElements = form.elements.length;
        for (i=0; i<nbElements; i++) {
            form.elements[i].checked = false;
        }
    }
</script>
<?php
function afficherResultat($tableau)
{
    static $i = 0;
    $i++;
    // Si c'est OK
    if (strpos($tableau[count($tableau) - 1], 'OK') !== false) {
        $resultat = 'OK';
        // Style du résumé
        $style = "background: #94D88B;";
    } else {
        $resultat = 'ERREURS';
        // Style du résumé
        $style = "background: #D89C8B;";
    }
    // Supprime la première ligne
    unset($tableau[0]);
    ?>
    <p style="<?=$style;?>">
        <a href="#detailErreurs<?=$i?>" onclick="ouvrir(document.getElementById('detailErreurs<?=$i?>'))">
            Résumé :
            <?=$resultat?></a>
    </p>
    <div id="detailErreurs<?=$i?>" style="display:none">
        <pre>
            <?=implode("\n", $tableau);?>
        </pre>
    </div>
    <?php
}
?>

<form name="tests" method="post" action="<?=$this->baseUrl?>/testsunitaires/executer">
    <h1>
        Tests unitaires
    </h1>
    <fieldset>
    <legend>Choisissez les tests unitaires que vous voulez lancer :</legend>
        <?php
        foreach ($this->librairies as $nom => $test) {
            $nomTest = $test['nom'];
            $checked = '';
            if (isset($_POST[$nomTest])) {
                $checked = 'checked="true"';
            }
            echo '<input type="checkbox" '.$checked.' name="'.$test['nom'].'" /> '. $nom;
        }
        ?>
    </fieldset>
    <input type="submit" value='Lancer les tests' />
    <input type="button" value='Tout décocher' onClick = "decocher()" />
</form>

<?php
    if ($this->post) {
        foreach ($this->librairies as $nom => $test) {
            if (isset($this->$test['nom'])) {
                echo '<h2>'.$nom.'</h2>';
                afficherResultat($this->$test['nom']);
            }
        }
    }
