<?php
// Formate l'affichage du nom d'un fichier
function formaterNomFichier($filename) {
	// Sépare à "controllers"
	$array = preg_split('#/controllers/#', $filename, 2);
	if (count($array) > 1) {
		$filename = $array[1];
	}
	// Sépare à "/views/scripts"
	$array = preg_split('#/views/scripts/#', $filename, 2);
	if (count($array) > 1) {
		$filename = $array[1];
	}
	// Sépare à "models"
	$array = preg_split('#/models/#', $filename, 2);
	if (count($array) > 1) {
		$filename = $array[1];
	}
	// Sépare à "/library/Mycsense/"
	$array = preg_split('#/library/Mycsense/#', $filename, 2);
	if (count($array) > 1) {
		$filename = $array[1];
	}
	// Sépare à "librairies"
	$array = preg_split('#/librairies/Mycsense/#', $filename, 2);
	if (count($array) > 1) {
		$filename = $array[1];
	}
	// Sépare à "trunk"
	$array = preg_split('#/home/dev/#', $filename, 2);
	if (count($array) > 1) {
		$filename = $array[1];
	}
	return $filename;
}

// Affiche le résumé des erreurs
function afficherResume($resultats) {
	$tableauFichiers = array();
	foreach ($resultats as $tableau) {
		$tableauFichiers = array_merge($tableauFichiers, $tableau);
	}
	// Compte le nombre d'erreurs
	$nbFichiers = 0;
	$nbErreurs = 0;
	$nbFichiersAvecErreur = 0;
	foreach ($tableauFichiers as $nomFichier => $listeErreurs) {
		$nbFichiers++;
		if (count($listeErreurs) > 0) {
			$nbFichiersAvecErreur++;
		}
		$nbErreurs += count($listeErreurs);
	}
	$pourcentageErreurs = (int) ($nbFichiersAvecErreur * 100 / $nbFichiers);
	?>
	<p>
		Pourcentage d'erreurs :
		<strong><?=$pourcentageErreurs?> %</strong>
	</p>
	<p style="margin-bottom: 20px">
		Nombre d'erreurs :
		<strong><?=$nbErreurs?></strong>
	</p>
	<?php
}

// Affiche le tableau des erreurs
function afficherErreurs($tableauFichiers) {
	?>
	<table class="tableauErreurs" summary="Liste des erreurs">
		<tr>
			<th style="width: 30%">
				Nom du fichier
			</th>
			<th style="width: 40px">
				Ligne
			</th>
			<th style="width: 30%">
				Description de l'erreur
			</th>
			<th>
				Contenu de la ligne
			</th>
		</tr>
		<?php
		foreach ($tableauFichiers as $nomFichier => $listeErreurs) {
			if (count($listeErreurs) == 0) {
				?>
				<tr>
					<td class="nomFichier">
						<?=formaterNomFichier($nomFichier)?>
					</td>
					<td>
					</td>
					<td class="descriptionOk">
						OK
					</td>
					<td>
					</td>
				</tr>
				<?php
			} else {
				foreach ($listeErreurs as $erreur) {
					?>
					<tr>
						<td class="nomFichier">
							<?=formaterNomFichier($nomFichier)?>
						</td>
						<td class="numLigne">
							<?=$erreur['numLigne']?>
						</td>
						<td class="descriptionErreur">
							<?=$erreur['description']?>
						</td>
						<td class="codeLigne">
							<?=htmlentities($erreur['ligne'])?>
						</td>
					</tr>
					<?php
				}
			}
		}
		?>
	</table>
	<?php
}
?>

<h1>Librairie</h1>
<?php
$resultatValidation = $this->librairie;
afficherResume($resultatValidation);
$librairie = $resultatValidation['librairie'];
afficherErreurs($librairie);
?>

<h1>Base Carbone</h1>
<?php
$resultatValidation = $this->basecarbone;
afficherResume($resultatValidation);
?>

<h2>Contrôleurs</h2>
<?php
$controleurs = $resultatValidation['controleurs'];
afficherErreurs($controleurs);
?>

<h2>Vues</h2>
<?php
$vues = $resultatValidation['vues'];
afficherErreurs($vues);
?>

<h2>Modèle</h2>
<?php
$modele = $resultatValidation['modele'];
afficherErreurs($modele);
?>

<h2>Librairie</h2>
<?php
$librairie = $resultatValidation['librairie'];
afficherErreurs($librairie);
?>


<h1>Stations de montagne</h1>
<?php
$resultatValidation = $this->stationsmontagne;
afficherResume($resultatValidation);
?>

<h2>Contrôleurs</h2>
<?php
$controleurs = $resultatValidation['controleurs'];
afficherErreurs($controleurs);
?>

<h2>Vues</h2>
<?php
$vues = $resultatValidation['vues'];
afficherErreurs($vues);
?>

<h2>Modèle</h2>
<?php
$modele = $resultatValidation['modele'];
afficherErreurs($modele);
?>

<h2>Librairie</h2>
<?php
$librairie = $resultatValidation['librairie'];
afficherErreurs($librairie);
?>


<h1>Unites</h1>
<?php
$resultatValidation = $this->unites;
afficherResume($resultatValidation);
?>

<h2>Contrôleurs</h2>
<?php
$controleurs = $resultatValidation['controleurs'];
afficherErreurs($controleurs);
?>

<h2>Vues</h2>
<?php
$vues = $resultatValidation['vues'];
afficherErreurs($vues);
?>

<h2>Modèle</h2>
<?php
$modele = $resultatValidation['modele'];
afficherErreurs($modele);
?>

<h2>Librairie</h2>
<?php
$librairie = $resultatValidation['librairie'];
afficherErreurs($librairie);
?>


<h1>Utilisateurs</h1>
<?php
$resultatValidation = $this->utilisateurs;
afficherResume($resultatValidation);
?>

<h2>Contrôleurs</h2>
<?php
$controleurs = $resultatValidation['controleurs'];
afficherErreurs($controleurs);
?>

<h2>Vues</h2>
<?php
$vues = $resultatValidation['vues'];
afficherErreurs($vues);
?>

<h2>Modèle</h2>
<?php
$modele = $resultatValidation['modele'];
afficherErreurs($modele);
?>

<h2>Librairie</h2>
<?php
$librairie = $resultatValidation['librairie'];
afficherErreurs($librairie);
?>


<h1>ACL</h1>
<?php
$resultatValidation = $this->acl;
afficherResume($resultatValidation);
?>

<h2>Contrôleurs</h2>
<?php
$controleurs = $resultatValidation['controleurs'];
afficherErreurs($controleurs);
?>

<h2>Vues</h2>
<?php
$vues = $resultatValidation['vues'];
afficherErreurs($vues);
?>

<h2>Modèle</h2>
<?php
$modele = $resultatValidation['modele'];
afficherErreurs($modele);
?>

<h2>Librairie</h2>
<?php
$librairie = $resultatValidation['librairie'];
afficherErreurs($librairie);
?>


<h1>Pages et menus</h1>
<?php
$resultatValidation = $this->pagesmenus;
afficherResume($resultatValidation);
?>

<h2>Contrôleurs</h2>
<?php
$resultatValidation = $this->pagesmenus;
$controleurs = $resultatValidation['controleurs'];
afficherErreurs($controleurs);
?>

<h2>Vues</h2>
<?php
$vues = $resultatValidation['vues'];
afficherErreurs($vues);
?>

<h2>Modèle</h2>
<?php
$modele = $resultatValidation['modele'];
afficherErreurs($modele);
?>

<h2>Librairie</h2>
<?php
$librairie = $resultatValidation['librairie'];
afficherErreurs($librairie);
?>


<h1>Langues</h1>
<?php
$resultatValidation = $this->langues;
afficherResume($resultatValidation);
?>

<h2>Contrôleurs</h2>
<?php
$resultatValidation = $this->langues;
$controleurs = $resultatValidation['controleurs'];
afficherErreurs($controleurs);
?>

<h2>Vues</h2>
<?php
$vues = $resultatValidation['vues'];
afficherErreurs($vues);
?>

<h2>Modèle</h2>
<?php
$modele = $resultatValidation['modele'];
afficherErreurs($modele);
?>

<h2>Librairie</h2>
<?php
$librairie = $resultatValidation['librairie'];
afficherErreurs($librairie);
?>


<h1>Supervision</h1>
<?php
$resultatValidation = $this->supervision;
afficherResume($resultatValidation);
?>

<h2>Contrôleurs</h2>
<?php
$resultatValidation = $this->supervision;
$controleurs = $resultatValidation['controleurs'];
afficherErreurs($controleurs);
?>

<h2>Vues</h2>
<?php
$vues = $resultatValidation['vues'];
afficherErreurs($vues);
?>

<h2>Modèle</h2>
<?php
$modele = $resultatValidation['modele'];
afficherErreurs($modele);
?>

<h2>Librairie</h2>
<?php
$librairie = $resultatValidation['librairie'];
afficherErreurs($librairie);
?>
