<h2><?=$this->error['code']?></h2>

<p>
    <?=$this->error['message']?>
</p>

<?php
    $boutonRetour = new UI_HTML_Button(__('UI', 'button', 'previousPage'));
    $boutonRetour->addEvent("onclick", "history.back();");
    $boutonRetour->render();
?>

<?php
    if ((APPLICATION_ENV == 'testsunitaires')
        || (APPLICATION_ENV == 'developpement')
        || (APPLICATION_ENV == 'test')
    ) {
?>

<h2>Information complémentaire pour l'environnement : <?=APPLICATION_ENV?></h2>

    <h3>Informations sur l'erreur:</h3>
    <p>
        <b>Message :</b> <?=$this->error['message']?>
    </p>

    <h3>Trace d'exécution:</h3>
    <pre><?=$this->error['error']->exception->getTraceAsString()?></pre>

    <h3>Paramètres de la requête HTTP :</h3>
    <pre><?=var_export($this->error['error']->request->getParams(), true)?></pre>

<?php
    }
