<h1>Une erreur est survenue</h1>

<h2><?php echo $this->message ?></h2>

<?php
if ((APPLICATION_ENV == 'testsunitaires') || (APPLICATION_ENV == 'developpement') || (APPLICATION_ENV == 'test')) :
?>

	<h3>Informations sur l'erreur :</h3>
	<p>
		<b>Message :</b> <?php echo $this->exception->getMessage() ?>
	</p>

	<h3>Trace :</h3>
	<pre><?php echo $this->exception->getTraceAsString() ?>
	</pre>

	<h3>Paramètres de la requête :</h3>
	<pre><?php echo var_export($this->request->getParams(), true) ?>
	</pre>

<?php
endif
?>